  version: '3'
    
  services:

        
    # gunicorn_api_server:
    #   build: .
    #   command: bash -c "pip install gunicorn && python manage.py migrate && gunicorn wololo.wsgi:application --timeout 300 --bind 0.0.0.0:8000
    #   volumes:
    #     - .:/code
    #   expose:
    #     - 8000
    #   depends_on:
    #     - db

    db:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      env_file: deployment/.env

    web:
      build: .
      command: python manage.py runserver 0.0.0.0:8000 --settings=wololo_project.settings.prod
      env_file: deployment/.env
      ports:
        - "8000:8000"
      links:
        - redis

    redis: 
      image: redis
      command: redis-server
      ports: 
        - '6379:6379'

    # worker_channels:
    #   build: .
    #   command: python manage.py runworker --settings=wololo_project.settings.prod
    #   env_file: deployment/.env
    #   links:
    #     - redis

    channels: 
      build: .
      command: daphne -b 0.0.0.0 -p 8001 wololo_project.asgi:channel_layer
      env_file: deployment/.env
      ports: 
        - "8001:8001"
      links: 
        - redis

  volumes:
    postgres_data: