# Generated by Django 2.1.5 on 2019-04-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wololo', '0003_villages_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='villages',
            name='has_all_buildings',
            field=models.BooleanField(default=False),
        ),
    ]
