# Generated by Django 2.1.5 on 2019-04-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wololo', '0007_auto_20190423_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villagetroops',
            name='village_id',
        ),
        migrations.AddField(
            model_name='villages',
            name='has_village_troops',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='VillageTroops',
        ),
    ]
