# Generated by Django 2.1.5 on 2019-04-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wololo', '0011_auto_20190423_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='number_of_villages',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
