# Generated by Django 2.1.5 on 2019-04-23 18:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wololo', '0006_villagebuildings_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villagetroops',
            name='in_village_quantity',
        ),
        migrations.RemoveField(
            model_name='villagetroops',
            name='on_move_quantity',
        ),
        migrations.RemoveField(
            model_name='villagetroops',
            name='total_quantity',
        ),
        migrations.RemoveField(
            model_name='villagetroops',
            name='unit_name',
        ),
        migrations.RemoveField(
            model_name='villagetroops',
            name='unit_type',
        ),
        migrations.AddField(
            model_name='villagetroops',
            name='in_village_troops_quantity',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'cavalry': {'Heavy Cavalry': 0, 'Light Cavalry': 0, 'Scout': 0}, 'infantry': {'Archer': 0, 'Axeman': 0, 'Spearman': 0, 'Swordsman': 0}, 'siegeWeapons': {'Catapult': 0, 'Ram': 0}}),
        ),
        migrations.AddField(
            model_name='villagetroops',
            name='on_move_troops_quantity',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'cavalry': {'Heavy Cavalry': 0, 'Light Cavalry': 0, 'Scout': 0}, 'infantry': {'Archer': 0, 'Axeman': 0, 'Spearman': 0, 'Swordsman': 0}, 'siegeWeapons': {'Catapult': 0, 'Ram': 0}}),
        ),
        migrations.AddField(
            model_name='villagetroops',
            name='total_troops_quantity',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'cavalry': {'Heavy Cavalry': 0, 'Light Cavalry': 0, 'Scout': 0}, 'infantry': {'Archer': 0, 'Axeman': 0, 'Spearman': 0, 'Swordsman': 0}, 'siegeWeapons': {'Catapult': 0, 'Ram': 0}}),
        ),
        migrations.AlterField(
            model_name='villagetroops',
            name='village_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='villagetroopss', to='wololo.Villages'),
        ),
    ]
