# Generated by Django 2.1.5 on 2019-04-23 19:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wololo', '0008_auto_20190423_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='VillageTroops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_village_troops_quantity_json', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('on_move_troops_quantity_json', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('total_troops_quantity_json', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('village_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='villagetroopss', to='wololo.Villages')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
