# Generated by Django 2.1.5 on 2019-04-23 19:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import wololo.models


class Migration(migrations.Migration):

    dependencies = [
        ('wololo', '0009_villagetroops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villagetroops',
            name='in_village_troops_quantity_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=wololo.models.default_fresh_troops_dict),
        ),
        migrations.AlterField(
            model_name='villagetroops',
            name='on_move_troops_quantity_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=wololo.models.default_fresh_troops_dict),
        ),
        migrations.AlterField(
            model_name='villagetroops',
            name='total_troops_quantity_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=wololo.models.default_fresh_troops_dict),
        ),
    ]
