# Generated by Django 2.1.5 on 2019-04-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wololo', '0010_auto_20190423_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='troopmovements',
            name='movement_type',
            field=models.CharField(default='attack', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='troopmovements',
            name='state',
            field=models.CharField(default='going', max_length=9),
            preserve_default=False,
        ),
    ]
