# Generated by Django 2.1.5 on 2019-04-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wololo', '0012_users_number_of_villages'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
