# Generated by Django 2.1.7 on 2019-06-01 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wololo', '0013_users_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battlereports',
            old_name='attacker_id',
            new_name='attacker',
        ),
        migrations.RenameField(
            model_name='battlereports',
            old_name='defender_id',
            new_name='defender',
        ),
        migrations.RenameField(
            model_name='reports',
            old_name='sended_to_user_id',
            new_name='sended_to_user',
        ),
        migrations.RenameField(
            model_name='trainingqueue',
            old_name='village_id',
            new_name='village',
        ),
        migrations.RenameField(
            model_name='troopmovements',
            old_name='home_village_id',
            new_name='home_village',
        ),
        migrations.RenameField(
            model_name='troopmovements',
            old_name='target_village_id',
            new_name='target_village',
        ),
        migrations.RenameField(
            model_name='villagebuildings',
            old_name='village_id',
            new_name='village',
        ),
        migrations.RenameField(
            model_name='villages',
            old_name='region_id',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='villages',
            old_name='user_id',
            new_name='user',
        ),
    ]
