# Generated by Django 2.2.2 on 2019-07-08 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wololo', '0016_auto_20190708_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingqueue',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trainingqueue',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_queues', to='wololo.Villages'),
        ),
        migrations.AlterField(
            model_name='villagebuildings',
            name='resource_building_detail_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='village_building', to='wololo.ResourceBuildingDetails'),
        ),
        migrations.AlterField(
            model_name='villagebuildings',
            name='upgrading_details_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='village_building', to='wololo.UpgradingDetails'),
        ),
        migrations.AlterField(
            model_name='villagebuildings',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='village_buildings', to='wololo.Villages'),
        ),
    ]
