# Generated by Django 2.2.2 on 2019-07-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wololo', '0017_auto_20190708_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battlereports',
            old_name='report_id',
            new_name='report',
        ),
        migrations.AlterField(
            model_name='reports',
            name='type',
            field=models.CharField(choices=[('battle', 'Battle')], max_length=15),
        ),
    ]
