# Generated by Django 2.2.2 on 2019-07-08 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wololo', '0018_auto_20190708_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battlereports',
            old_name='attacker_battle_result_id',
            new_name='attacker_battle_result',
        ),
        migrations.RenameField(
            model_name='battlereports',
            old_name='defender_battle_result_id',
            new_name='defender_battle_result',
        ),
    ]
