# Generated by Django 2.2.2 on 2019-07-08 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wololo', '0019_auto_20190708_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
