# Generated by Django 2.2.2 on 2019-07-10 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wololo', '0022_auto_20190708_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battleresults',
            old_name='attacker_result',
            new_name='result',
        ),
        migrations.AlterField(
            model_name='battlereports',
            name='attacker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battlereport', to=settings.AUTH_USER_MODEL),
        ),
    ]
