# Generated by Django 2.2.2 on 2019-07-10 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wololo', '0023_auto_20190710_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regions',
            old_name='region_name',
            new_name='name',
        ),
    ]
