# Generated by Django 2.2.2 on 2019-11-03 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wololo', '0025_auto_20191103_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlereports',
            name='attacker_battle_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battlereportss', to='wololo.BattleResults'),
        ),
        migrations.AlterField(
            model_name='battlereports',
            name='defender_battle_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battlereportss_2', to='wololo.BattleResults'),
        ),
    ]
