# Generated by Django 3.0.5 on 2020-05-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wololo', '0026_auto_20191103_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='villagetroops',
            old_name='village_id',
            new_name='village',
        ),
    ]
