# Generated by Django 3.0.5 on 2020-05-26 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wololo', '0027_auto_20200523_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='number_of_villages',
        ),
    ]
