# Generated by Django 2.1.5 on 2019-04-22 20:25

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wololo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_details_hidden', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='BattleResults',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_and_losses_troops_json', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=15)),
                ('is_viewed', models.BooleanField(default=False)),
                ('sended_to_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='ResourceBuildingDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_interaction_date', models.DateTimeField()),
                ('sum', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='TrainingQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_id', models.TextField(max_length=100)),
                ('unit_name', models.CharField(max_length=30)),
                ('unit_type', models.CharField(max_length=30)),
                ('units_left', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField()),
                ('will_end_at', models.DateTimeField()),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='TroopMovements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.TextField(max_length=100)),
                ('arrival_time', models.DateTimeField()),
                ('moving_troops_json', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='UpgradingDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_id', models.CharField(max_length=30)),
                ('started_upgrading_at', models.DateTimeField()),
                ('will_be_upgraded_at', models.DateTimeField()),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='VillageBuildings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=30)),
                ('is_upgrading', models.BooleanField(default=False)),
                ('is_resource_building', models.BooleanField(default=False)),
                ('resource_building_detail_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='villagebuildingss', to='wololo.ResourceBuildingDetails')),
                ('upgrading_details_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='villagebuildingss', to='wololo.UpgradingDetails')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Villages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('village_name', models.CharField(max_length=20)),
                ('coords_x', models.IntegerField()),
                ('coords_y', models.IntegerField()),
                ('region_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villagess', to='wololo.Regions')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='villagess', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='VillageTroops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=30)),
                ('unit_type', models.CharField(max_length=30)),
                ('on_move_quantity', models.PositiveIntegerField(default=0)),
                ('in_village_quantity', models.PositiveIntegerField(default=0)),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('village_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villagetroopss', to='wololo.Villages')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.AddField(
            model_name='villagebuildings',
            name='village_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villagebuildingss', to='wololo.Villages'),
        ),
        migrations.AddField(
            model_name='troopmovements',
            name='home_village_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='troopmovementss', to='wololo.Villages'),
        ),
        migrations.AddField(
            model_name='troopmovements',
            name='target_village_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='troopmovementss_2', to='wololo.Villages'),
        ),
        migrations.AddField(
            model_name='trainingqueue',
            name='village_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainingqueues', to='wololo.Villages'),
        ),
        migrations.AddField(
            model_name='battlereports',
            name='attacker_battle_result_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='battlereportss', to='wololo.BattleResults'),
        ),
        migrations.AddField(
            model_name='battlereports',
            name='attacker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battlereportss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='battlereports',
            name='defender_battle_result_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='battlereportss_2', to='wololo.BattleResults'),
        ),
        migrations.AddField(
            model_name='battlereports',
            name='defender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battlereportss_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='battlereports',
            name='report_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='battlereportss', to='wololo.Reports'),
        ),
    ]
