# Generated by Django 2.1.5 on 2019-04-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wololo', '0002_auto_20190422_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='villages',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
