# Generated by Django 2.1.5 on 2019-04-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wololo', '0004_villages_has_all_buildings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcebuildingdetails',
            name='last_interaction_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
