# Generated by Django 2.2.2 on 2019-07-08 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wololo', '0021_battleresults_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battleresults',
            old_name='result',
            new_name='attacker_result',
        ),
        migrations.AddField(
            model_name='battlereports',
            name='attacker_village',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, related_name='attack_br', to='wololo.Villages'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battlereports',
            name='defender_village',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='defend_br', to='wololo.Villages'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='battlereports',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wololo.Reports'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='sended_to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
