# Generated by Django 2.2.2 on 2019-11-03 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wololo', '0024_auto_20190710_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='troopmovements',
            name='movement_duration_seconds',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='villages',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='villages', to=settings.AUTH_USER_MODEL),
        ),
    ]
